#Day 8


In [1]:
import numpy as np
a=np.random.random((2,2))
b=np.random.random((4,3,2))
c=np.random.random((5,4,3,2))

In [6]:
a


array([[0.9448257 , 0.0302145 ],
       [0.34630308, 0.5829545 ]])

In [9]:
a[0][1]
a[:,0] #first column of every row

array([0.9448257 , 0.34630308])

In [17]:
#print(c[0])

print(c[0,1])

#print(c[0,1,2])

[[0.83165284 0.19219835]
 [0.63625691 0.36709309]
 [0.52424169 0.5500114 ]]


In [18]:
np.sum(a)

1.904297774323822

In [19]:
a.sum(axis=0) #sum of rows among columns
a.sum(axis=1) #sum of colums among rows

array([1.29112878, 0.613169  ])

In [22]:
b

array([[[0.39592356, 0.4606387 ],
        [0.59296798, 0.51518657],
        [0.13002972, 0.73268714]],

       [[0.87622035, 0.23642405],
        [0.29276106, 0.35377054],
        [0.26657863, 0.0935377 ]],

       [[0.4480998 , 0.51692773],
        [0.99454038, 0.23001841],
        [0.46307167, 0.17715015]],

       [[0.29622696, 0.73076054],
        [0.64556476, 0.93973425],
        [0.94253005, 0.86251848]]])

In [20]:
b.mean()

0.5080778819729047

In [21]:
b.mean(axis=0) #mean

array([[0.50411767, 0.48618775],
       [0.63145854, 0.50967744],
       [0.45055252, 0.46647337]])

In [23]:
b.mean(axis=2)

array([[0.42828113, 0.55407728, 0.43135843],
       [0.5563222 , 0.3232658 , 0.18005817],
       [0.48251376, 0.6122794 , 0.32011091],
       [0.51349375, 0.7926495 , 0.90252426]])

In [25]:
b.mean(axis=1)

array([[0.37297375, 0.56950414],
       [0.47852001, 0.22791076],
       [0.63523728, 0.3080321 ],
       [0.62810726, 0.84433775]])

In [26]:
b+2

array([[[2.39592356, 2.4606387 ],
        [2.59296798, 2.51518657],
        [2.13002972, 2.73268714]],

       [[2.87622035, 2.23642405],
        [2.29276106, 2.35377054],
        [2.26657863, 2.0935377 ]],

       [[2.4480998 , 2.51692773],
        [2.99454038, 2.23001841],
        [2.46307167, 2.17715015]],

       [[2.29622696, 2.73076054],
        [2.64556476, 2.93973425],
        [2.94253005, 2.86251848]]])

In [36]:
a=np.random.random((2,2))
b=np.random.random((2,2))

In [37]:
a,b

(array([[0.49542218, 0.62733915],
        [0.12754376, 0.50690011]]), array([[0.98485329, 0.218472  ],
        [0.98216778, 0.58990132]]))

In [29]:
a,b #sum of 2 matrices

(array([[0.9448257 , 0.0302145 ],
        [0.34630308, 0.5829545 ]]), array([[[0.39592356, 0.4606387 ],
         [0.59296798, 0.51518657],
         [0.13002972, 0.73268714]],
 
        [[0.87622035, 0.23642405],
         [0.29276106, 0.35377054],
         [0.26657863, 0.0935377 ]],
 
        [[0.4480998 , 0.51692773],
         [0.99454038, 0.23001841],
         [0.46307167, 0.17715015]],
 
        [[0.29622696, 0.73076054],
         [0.64556476, 0.93973425],
         [0.94253005, 0.86251848]]]))

In [ ]:
np.add(a,b)#same out put = sum

In [38]:
a-b

array([[-0.48943111,  0.40886716],
       [-0.85462402, -0.08300121]])

In [39]:
np.multiply(a,b)#matric multplication firt row per first column and so on

array([[0.48791816, 0.13705604],
       [0.12526937, 0.29902105]])

In [40]:
np.matmul(a,b)#multplication mathématiques

array([[1.10407046, 0.47830407],
       [0.62347284, 0.32688578]])

In [41]:
np.divide(a,b) #divide elements by elements

array([[0.50304161, 2.87148543],
       [0.12985944, 0.85929646]])

In [42]:
import os

In [ ]:
#osgetcwd() get current working directoy
#os.chdir() change working directory
#os.pathjoin() create a path
#if defined path already exists create it

In [ ]:
#open a file

#open(file, mode) "r"read "a"append "w"write "x"create

#additional mode "t"texte "b"binary