In [6]:


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.




"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""




"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

1.16.2


'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'

In [4]:
#1. Import the NUMPY package under the name np.

import numpy as np

1.16.2


In [7]:
#2. Print the NUMPY version and the configuration.

print(np.version.version)

1.16.2


In [44]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy waysthat use numpy to generate random arrays. Ho
#4. Print a.

a = np.random.random((2,3,5))
print(a)

b=np.random.rand(2,3,5)
print(b)

c=np.arange(30).reshape(2,3,5)
print(c)

[[[0.84713217 0.82206656 0.95159612 0.10216909 0.06620945]
  [0.06845051 0.80644511 0.48998281 0.9565273  0.32142801]
  [0.12359965 0.31525542 0.33962461 0.74599499 0.24019075]]

 [[0.91794517 0.85108931 0.12667595 0.79667968 0.86751142]
  [0.33607066 0.15351993 0.16524611 0.11857186 0.98496473]
  [0.49518832 0.67840793 0.36397945 0.47374935 0.92770865]]]
[[[0.13298014 0.3519745  0.37779748 0.96128967 0.86582095]
  [0.01529678 0.23376344 0.1588315  0.35969672 0.43805312]
  [0.15750628 0.56250995 0.67643109 0.85338589 0.50341071]]

 [[0.06786873 0.44153315 0.37128214 0.71948478 0.33086796]
  [0.96401072 0.97803502 0.40043238 0.90292806 0.77339884]
  [0.82640994 0.1277549  0.79041299 0.50931487 0.37125955]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [45]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
#6. Print b.

b=np.tile(1, (5, 2,3))
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [46]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(np.size(a) == np.size(b))
print(np.shape(a) == np.shape(b))

True
False


In [47]:
#8. Are you able to add a and b? Why or why not?

np.add(a,b)

#they don´t have the same shape 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [48]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c=np.transpose(b).reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [49]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d=np.add(a,c)
print(d)

#because they have the same shape

[[[1.84713217 1.82206656 1.95159612 1.10216909 1.06620945]
  [1.06845051 1.80644511 1.48998281 1.9565273  1.32142801]
  [1.12359965 1.31525542 1.33962461 1.74599499 1.24019075]]

 [[1.91794517 1.85108931 1.12667595 1.79667968 1.86751142]
  [1.33607066 1.15351993 1.16524611 1.11857186 1.98496473]
  [1.49518832 1.67840793 1.36397945 1.47374935 1.92770865]]]


In [50]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)

print(d)

#we hve add 1 to all the values


[[[0.84713217 0.82206656 0.95159612 0.10216909 0.06620945]
  [0.06845051 0.80644511 0.48998281 0.9565273  0.32142801]
  [0.12359965 0.31525542 0.33962461 0.74599499 0.24019075]]

 [[0.91794517 0.85108931 0.12667595 0.79667968 0.86751142]
  [0.33607066 0.15351993 0.16524611 0.11857186 0.98496473]
  [0.49518832 0.67840793 0.36397945 0.47374935 0.92770865]]]
[[[1.84713217 1.82206656 1.95159612 1.10216909 1.06620945]
  [1.06845051 1.80644511 1.48998281 1.9565273  1.32142801]
  [1.12359965 1.31525542 1.33962461 1.74599499 1.24019075]]

 [[1.91794517 1.85108931 1.12667595 1.79667968 1.86751142]
  [1.33607066 1.15351993 1.16524611 1.11857186 1.98496473]
  [1.49518832 1.67840793 1.36397945 1.47374935 1.92770865]]]


In [52]:
#12. Multiply a and c. Assign the result to e.

e = np.multiply(a,c)
print(e)

[[[0.84713217 0.82206656 0.95159612 0.10216909 0.06620945]
  [0.06845051 0.80644511 0.48998281 0.9565273  0.32142801]
  [0.12359965 0.31525542 0.33962461 0.74599499 0.24019075]]

 [[0.91794517 0.85108931 0.12667595 0.79667968 0.86751142]
  [0.33607066 0.15351993 0.16524611 0.11857186 0.98496473]
  [0.49518832 0.67840793 0.36397945 0.47374935 0.92770865]]]


In [55]:
#13. Does e equal to a? Why or why not?

print(a == e)

#because multiplying matrix is not the same as multiplying every value per 1

[[[False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]
  [False False False False False]]]


In [58]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
print(d_max)
d_min =np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

1.984964733044734
1.0662094542524385
1.5151327029321446


In [63]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty([2,3,5]
print(f)


[[[0.84713217 0.82206656 0.95159612 0.10216909 0.06620945]
  [0.06845051 0.80644511 0.48998281 0.9565273  0.32142801]
  [0.12359965 0.31525542 0.33962461 0.74599499 0.24019075]]

 [[0.91794517 0.85108931 0.12667595 0.79667968 0.86751142]
  [0.33607066 0.15351993 0.16524611 0.11857186 0.98496473]
  [0.49518832 0.67840793 0.36397945 0.47374935 0.92770865]]]


In [ ]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

In [65]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d_min<d[i][j][k]<d_mean:
                f[i][j][k]=25
            elif d_mean<d[i][j][k]<d_max:
                f[i][j][k]=75
            elif d[i][j][k]==d_mean:
                f[i][j][k]=50
            elif d[i][j][k]==d_min:
                f[i][j][k]=0
            elif d[i][j][k]==d_max:
                f[i][j][k]=100
        
print(f)

[[[ 75.  75.  75.  25.   0.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  75.  25.  75.  75.]
  [ 25.  25.  25.  25. 100.]
  [ 25.  75.  25.  25.  75.]]]


In [66]:
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
       # [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
       # [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       #[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
       # [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
       # [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
       # [ 75.,  75.,  25.,  25.,  25.],
       # [ 75.,  25.,  75.,  75.,  75.]],

      # [[ 25.,  25.,  25.,  25., 100.],
      #  [ 75.,  75.,  75.,  75.,  75.],
      #  [ 25.,  75.,   0.,  75.,  75.]]])
    
    
print(d)

[[[1.84713217 1.82206656 1.95159612 1.10216909 1.06620945]
  [1.06845051 1.80644511 1.48998281 1.9565273  1.32142801]
  [1.12359965 1.31525542 1.33962461 1.74599499 1.24019075]]

 [[1.91794517 1.85108931 1.12667595 1.79667968 1.86751142]
  [1.33607066 1.15351993 1.16524611 1.11857186 1.98496473]
  [1.49518832 1.67840793 1.36397945 1.47374935 1.92770865]]]


In [70]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
       # [ 'D',  'D',  'B',  'B',  'B'],
       # [ 'D',  'B',  'D',  'D',  'D']],

      # [[ 'B',  'B',  'B',  'B',  'E'],
      #  [ 'D',  'D',  'D',  'D',  'D'],
      #  [ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.

f = np.empty([2,3,5], str)
print(f)

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d_min<d[i][j][k]<d_mean:
                f[i][j][k]="B"
            elif d_mean<d[i][j][k]<d_max:
                f[i][j][k]="D"
            elif d[i][j][k]==d_mean:
                f[i][j][k]="C"
            elif d[i][j][k]==d_min:
                f[i][j][k]="A"
            elif d[i][j][k]==d_max:
                f[i][j][k]="E"

print(f)


[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]
[[['D' 'D' 'D' 'B' 'A']
  ['B' 'D' 'B' 'D' 'B']
  ['B' 'B' 'B' 'D' 'B']]

 [['D' 'D' 'B' 'D' 'D']
  ['B' 'B' 'B' 'B' 'E']
  ['B' 'D' 'B' 'B' 'D']]]
